@entrypoint = http://localhost:9000

GET {{entrypoint}}/users

###
GET {{entrypoint}}/users/3

###
POST {{entrypoint}}/signup
Content-type: application/json

{
   "username": "test",
   "email": "test@test.com",
   "password": "testtest",
   "passwordConfirm": "testtest",
   "role_id": 2
}