@entrypoint = http://localhost:9000

GET {{entrypoint}}/users

###
GET {{entrypoint}}/users/1

###
POST {{entrypoint}}/signup
Content-type: application/json

{
   "username": "gtn",
   "email": "gtn@gtn.com",
   "password": "gtn"
}